name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: |
          npm config set '@fortawesome:registry' '${{ secrets.FONTAWESOME_REGISTRY }}'
          npm config set '//harding.dev:23435/:_authToken' '${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}'
          yarn install

      # TODO: code coverage, reporting, break these steps up
      - run: yarn format
      - run: yarn lint
      - run: yarn test
      - run: yarn build
